### ISSUE TITLE
Template Controller

### ISSUE THREAD

**Issue by moshloop** [flanksource/git-operator#14]
Modeled a little on the namespace configurator, but more generic

```yaml
kind: Template
spec:
      kind: gitpullrequest
      namespaceSelector:
           matchLabels:
      objectSelector: 
           matchLabels:
      objectFilters:
           - $.status.comments.*.message == '/preview' # only deploy pull requests that have the /preview comment
      resources:
          - kind: Namespace
            apiVersion: v1
            metadata:
                   name: "pr-{{ .id}}
                   annotations:
                        description: "{{.name}}"
                        author: "{{.description}}"
          - kind: GitOps
             spec:
                 repo: "{{.url}}"        
```
